#   Formato mensagem dos logs
LOGS_FORMATTER = "[ %(asctime)s ] - %(message)s"

#   Formato data/hora logs
LOGS_DATE_FORMAT = "%d-%m-%Y %H:%M:%S"

#   Constantes para ações de logs
LOG_INSERIR = "*INSERIR*"
LOG_LISTAR = "*LISTAR*"
LOG_APAGAR = "*APAGAR*"
LOG_CONSULTAR = "*CONSULTAR*"
LOG_FOLHA = "*FOLHA_PG*"
LOG_EXPORTAR = "*EXPORTAR*"
LOG_IMPORTAR_J = "*IMPORTAR_JSON*"
LOG_IMPORTAR_C = "*IMPORTAR_CSV*"

LOG_INICIAR = "*INICIALIZOU*"
LOG_FIM = "*ENCERRANDO*"
LOG_LOCALE = "*LOCALE*"
LOG_CARREGAR = "*CARREGAR*"
LOG_CRIAR_J = "*CRIAR_JSON*"
LOG_CRIAR_C = "*CRIAR_CSV*"
